import tailwindcss from '@tailwindcss/vite';
import type { Plugin } from 'vite';
import { defineConfig } from 'vite';
import solidPlugin from 'vite-plugin-solid';

// Plugin to add banner to CSS files
function cssBannerPlugin(): Plugin {
  return {
    name: 'css-banner',
    transform(code: string, id: string) {
      if (id.endsWith('.css')) {
        const banner = `/*
⚠️  STOP — This file is auto-generated and will be overwritten!

This CSS is generated by Tailwind CSS v4 from the utility classes
used in src/admin/*.tsx files. Do not edit this file directly.

To make changes:
  1. Edit the component files in src/admin/
  2. Run: pnpm build
  3. Commit the updated built files
*/\n`;
        return {
          code: banner + code,
          map: null,
        };
      }
    },
  };
}

export default defineConfig({
  plugins: [solidPlugin(), tailwindcss(), cssBannerPlugin()],
  publicDir: false,
  build: {
    outDir: 'dist/admin',
    sourcemap: true,
    // Readable output makes it easier to spot unexpected changes (e.g. supply-chain injections)
    // in git diffs. There's no performance benefit to minification in this local-only environment.
    minify: false,
    lib: {
      entry: './src/admin/app.tsx',
      name: 'AdminApp',
      formats: ['iife'],
      fileName: 'admin',
    },
    rollupOptions: {
      output: {
        entryFileNames: 'admin.js',
        banner:
          '// ⚠️  STOP — This file is auto-generated and will be overwritten!\n// Edit src/admin/*.tsx files and run: pnpm build',
      },
    },
  },
});
