// Socket notification constants for MMM-FamilyChores

export const SocketNotifications = {
  // Frontend to Backend
  CONFIG_REQUEST: 'CONFIG_REQUEST',
  CHORE_TOGGLE: 'CHORE_TOGGLE',
  CHORE_REASSIGN: 'CHORE_REASSIGN',
  CHORE_UNDO: 'CHORE_UNDO',

  // Backend to Frontend
  CONFIG_RESPONSE: 'CONFIG_RESPONSE',
  CHORE_DATA: 'CHORE_DATA',
  CHORE_UPDATE_RESULT: 'CHORE_UPDATE_RESULT',
  CHORE_REASSIGN_RESULT: 'CHORE_REASSIGN_RESULT',
  CHORE_UNDO_RESULT: 'CHORE_UNDO_RESULT',
  PIN_ERROR: 'PIN_ERROR',
} as const;
